### ISSUE TITLE
Requests to /dependencies with an unexpected Boot version fail with an internal server error

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/initializr#1033] opened 2019-11-07 15:16 UTC
A 500 response is returned due to the following exception being thrown:

```
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] java.lang.IllegalStateException: No suitable mapping was found for BillOfMaterials [groupId=org.springframework.cloud, artifactId=spring-cloud-dependencies, versionProperty=spring-cloud.version, order=50, additionalBoms=[], repositories=[]] and version 1.5.2.RELEASE
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at io.spring.initializr.metadata.BillOfMaterials.resolve(BillOfMaterials.java:208) ~[initializr-metadata-0.8.0.BUILD-SNAPSHOT.jar!/:na]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at io.spring.initializr.web.support.DefaultDependencyMetadataProvider.get(DefaultDependencyMetadataProvider.java:61) ~[initializr-web-0.8.0.BUILD-SNAPSHOT.jar!/:na]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_222]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_222]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_222]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:53) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:365) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:420) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at com.sun.proxy.$Proxy93.get(Unknown Source) ~[na:na]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at io.spring.initializr.web.controller.ProjectMetadataController.dependenciesFor(ProjectMetadataController.java:103) ~[initializr-web-0.8.0.BUILD-SNAPSHOT.jar!/:na]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at io.spring.initializr.web.controller.ProjectMetadataController.dependenciesV21(ProjectMetadataController.java:85) ~[initializr-web-0.8.0.BUILD-SNAPSHOT.jar!/:na]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_222]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_222]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_222]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_222]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88) ~[spring-boot-actuator-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.889+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114) ~[spring-boot-actuator-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104) ~[spring-boot-actuator-2.1.8.RELEASE.jar!/:2.1.8.RELEASE]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118) ~[spring-web-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:79) ~[client_certificate_mapper-1.11.0_RELEASE.jar!/:na]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.24.jar!/:9.0.24]
2019-11-07T15:11:17.890+00:00 [APP/PROC/WEB/0] [OUT] at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
```

**Comment by bono007** [comment] 2019-11-14 22:25
@wilkinsona 
@snicoll 

What is the desired behavior here? 400/badrequest or return 200 w/ a payload describing error?

**Comment by bono007** [comment] 2019-11-15 02:01
This happens when there is a dependency that points to a Bom and that Bom has mappings, none of which match the specified boot version range, then IllegalStateException is thrown. 

### Steps to repro:

1. Modify `/initializr/initializr-service-sample/src/main/resources/application.yml` 

```yaml
initializr:
  env:
    boms:
      my-api-bom:
        groupId: org.acme
        artifactId: my-api-bom
        versionProperty: my-api.version
        mappings:
        - compatibilityRange: "[2.0.0.RELEASE,2.1.6.RELEASE)"
          version: 1.0.0.RELEASE
          repositories: my-api-repo-1
        - compatibilityRange: "2.2.1.RELEASE"
          version: 2.0.0.RELEASE
          repositories: my-api-repo-2
    repositories:
      my-api-repo-1:
        name: repo1
        url: https://example.com/repo1
      my-api-repo-2:
        name: repo2
        url: https://example.com/repo2
  dependencies:
    - name: Other
      content:
        - name: My API
          id : my-api
          groupId: org.acme
          artifactId: my-api
          scope: provided
          bom: my-api-bom
```
2. Hit `http://localhost:8080/dependencies?bootVersion=1.5.2.RELEASE`

**Comment by snicoll** [comment] 2019-11-15 07:58
> This happens when there is a dependency that points to a Bom and that Bom has mappings, none of which match the specified boot version range

Thanks @bono007 and sorry for not writing that on the issue more explicitly but we were aware of the root cause already. We'd like to return a `400`, making sure the request is indeed invalid which may require some work. I can't unfortunately point you in the right direction without digging into the problem and I don't have the bandwidth to do that at the moment.

**Comment by bono007** [comment] 2019-11-15 23:45
@snicoll  no worries. Everytime I dig, I learn. And I understand you guys are busy w/ Boot stuff. 

I will take a stab at this anyways. Worst case, I learn more about metadata.

**Comment by snicoll** [comment] 2019-12-27 15:54
Closing in favour of PR #1039

**Closed by snicoll** 2019-12-27 15:54 UTC
Labels: type: bug
