### ISSUE TITLE
Upgrade to Spring Cloud Services 2.0.2.RELEASE/1.6.6.RELEASE

### ISSUE THREAD

**Issue by pivotal-dylan-roberts** [spring-io/initializr#757] opened 2018-10-26 11:01 UTC
New releases are on maven central

**Comment by pivotal-dylan-roberts** [comment] 2018-10-26 11:06
PRs #755 and #756 submitted.

**Comment by snicoll** [comment] 2018-10-26 11:16
Thanks but we don’t need an issue and a PR as one is a duplicate of the other.

**Closed by snicoll** 2018-10-26 11:16 UTC
