### ISSUE TITLE
MavenWrapperContributor throws StringIndexOutOfBoundsException in outer Tomcat

### ISSUE THREAD

**Issue by VancySavoki** [spring-io/initializr#894] opened 2019-04-17 09:18 UTC
I deploy `start.spring.io` with `initializr-generator-spring-0.8.0.BUILD-SNAPSHOT` into outer Tomcat,
MavenWrapperContributor will copy `classpath:maven/wrapper` into generated temp directory,
throws code
```java
41 String filename = resource.getURI().toString().substring(root.getURI().toString().length() + 1);

```

debug snapshots
![image](https://user-images.githubusercontent.com/9402727/56274167-d87e6f80-6130-11e9-88bf-18d21d52b73a.png)

**Comment by wilkinsona** [comment] 2019-04-17 09:24
Please take a moment to search for an existing issue before opening a new one. This is a duplicate of #827.

**Closed by wilkinsona** 2019-04-17 09:24 UTC
