### ISSUE TITLE
Add kafka stream binder to available stream binders

### ISSUE THREAD

**Issue by sobychacko** [spring-io/initializr#562] opened 2017-12-27 20:48 UTC
There is a new Kafka streams binder in spring cloud stream kafka support. It doesn't show up in the search in `start.spring.io`.

**Comment by snicoll** [comment] 2017-12-28 09:30
@sobychacko no need to create an issue and a PR. Thanks. 

Duplicate of #563

**Closed by snicoll** 2017-12-28 09:30 UTC
