### ISSUE TITLE
Issue in sprint boot version 2.4.0-M2 for apache kafka dependencies

### ISSUE THREAD

**Issue by shankarwww** [spring-io/initializr#1126] opened 2020-09-11 11:20 UTC
Hi All,

I am getting below error when using spring-cloud-stream-binder-kafka with version **2.4.0-M2**. But works fine with version **2.3.3.RELEASE**

```
The class hierarchy was loaded from the following locations:

    org.springframework.integration.dsl.IntegrationFlowBuilder: file:/C:/Users/sk/.m2/repository/org/springframework/integration/spring-integration-core/5.4.0-M2/spring-integration-core-5.4.0-M2.jar
    org.springframework.integration.dsl.IntegrationFlowDefinition: file:/C:/Users/sk/.m2/repository/org/springframework/integration/spring-integration-core/5.4.0-M2/spring-integration-core-5.4.0-M2.jar
    org.springframework.integration.dsl.BaseIntegrationFlowDefinition: file:/C:/Users/sk/.m2/repository/org/springframework/integration/spring-integration-core/5.4.0-M2/spring-integration-core-5.4.0-M2.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.integration.dsl.IntegrationFlowBuilder
```

Below is my pom:
-------------------

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.0-M2</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.sg.projects</groupId>
	<artifactId>demo-kafka</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo-kafka</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>Hoxton.SR8</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-streams</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-binder-kafka</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-r2dbc</artifactId>
		</dependency>
		<dependency>
			<groupId>io.r2dbc</groupId>
			<artifactId>r2dbc-postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
		</dependency>

	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by wilkinsona** [comment] 2020-09-11 11:37
Thanks for the report. Unfortunately, I have been unable to reproduce the problem with the pom that you have provided. Initially it failed as there was no URL for connecting to Postgres. Switching to H2 allowed the app to start successfully.

If you would like us to spend some more time investigating, please spend some time providing a complete yet minimal sample that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-issuemaster** [comment] 2020-09-18 11:40
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-09-25 11:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-09-25 11:40 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
