### ISSUE TITLE
Support for additional project generation settings

### ISSUE THREAD

**Issue by markpollack** [spring-io/initializr#824] opened 2019-02-11 21:02 UTC
It seems to me that a common use-case for extending initializr is to add some additional options to the project generation process.  For example, see this example of [hacking spring initializr](https://medium.com/@acetrike/hacking-spring-initializr-a081b5e35e08).  In my own case, I would like to add options to select among a few docker base images, customize the name of the docker path (as it often includes the location of a docker registry) and several other opt-in code generation steps for creating various bits of yaml for use in kubernetes or cloud foundry.  

Currently this would require adding properties to the `ProjectRequest` and then likely to `ProjectDescription` and `ResolvedProjectDescription`, so forking initializr which is something I would like to avoid.  I haven't experimented yet with just keeping the map of the form data around in the above three classes and seeing if that is good enough to solve my use-case, but would like to see some solution to avoid forking when adding some additional project generation options.

**Comment by markpollack** [comment] 2019-02-12 00:36
From my experiments with curl, something along the lines of https://github.com/markpollack/initializr/commit/b3f8747cdcc39d29bb43183d0f986d6b8fcb498d gets me pretty far for my needs

**Comment by mattyb678** [comment] 2019-03-15 17:43
I'm also needing to get some additional information from the client. @snicoll is @markpollack's approach the one you envision? I was thinking along the same lines as Mark, except I was thinking of it being a `Map<String, Object>`. Or do you have another approach in mind? 

I'm definitely happy to work on a PR for this 😄

**Comment by snicoll** [comment] 2019-03-16 06:20
@mattyb678 we haven't had the time to consider that feature in detail yet but as we have a strongly typed model, I don't really envision a generic `Map`. Thanks for offering a PR but Mark already shared a prototype we could reuse if we are heading in that direction.

**Comment by mattyb678** [comment] 2019-03-16 14:57
I was able to solve this by creating my own `ProjectGenerationInvoker` so that I could register my own beans based off what was in the `parameters` field of `WebProjectRequest` so maybe exposing the `ProjectGenerationContext` via customizers would allow people the flexibility to get the information from the client and not having to modify the `ProjectDescription` or `ResolvedProjectDescription`.

**Comment by snicoll** [comment] 2019-09-18 11:33
For the record, there is a way to bind additional attributes including registering a custom `ProjectDescription` to the project generation context, see [this note in the reference documentation](https://docs.spring.io/initializr/docs/current-SNAPSHOT/reference/html/#create-instance-advanced-config-custom-project-request). 

That doesn't require you to fork the library but it requires you to register a custom controller so that the `@ModelAttributes` binding work as expected. I prefer this option vs. extending `ProjectRequest` and `ProjectDescription` to allow random additional attributes. We're also revisit the web part in the future to make it more simple.

Duplicate of #990

**Closed by snicoll** 2019-09-18 11:33 UTC
Labels: status: pending-design-work, type: enhancement
