### ISSUE TITLE
Bug when creating a project with Spring Boot version >= 3 with Java version < 17

### ISSUE THREAD

**Issue by ala-ebi** [spring-io/initializr#1422] opened 2023-06-06 14:09 UTC
I am able to create projects using Spring Boot version 3.1.0 and Java 8 in the UI. However, the downloaded project has Java 17 in pom.xml

I would have expected the radio buttons for older Java versions to be disabled depending on the selected Spring version, or alternatively, an error message when trying to create the project, but not a project with a different version.

**Comment by snicoll** [comment] 2023-06-06 14:11
Thanks for the report, but that's the wrong issue tracker. start.spring.io has a GitHub link that points to its issue tracker. This is also a duplicate of https://github.com/spring-io/start.spring.io/issues/1041

**Closed by snicoll** 2023-06-06 14:11 UTC
