### ISSUE TITLE
Provide extension points before and after project structure generation

### ISSUE THREAD

**Issue by sivaprasadreddy** [spring-io/initializr#806] opened 2019-01-31 16:17 UTC
Currently while generating the project some configuration files, such as **.gitignore**, **application.properties** etc, are being created. 

**io.spring.initializr.generator.ProjectGenerator**

```
       protected File generateProjectStructure(ProjectRequest request,
			Map<String, Object> model) {
		File rootDir;
		try {
			rootDir = File.createTempFile("tmp", "", getTemporaryDirectory());
		}
		catch (IOException ex) {
			throw new IllegalStateException("Cannot create temp dir", ex);
		}
		addTempFile(rootDir.getName(), rootDir);
		rootDir.delete();
		rootDir.mkdirs();

		File dir = initializerProjectDir(rootDir, request);
		....
                 ....
		generateGitIgnore(dir, request);
                 ....
                 ....
		File resources = new File(dir, "src/main/resources");
		resources.mkdirs();
		writeText(new File(resources, "application.properties"), "");

		return rootDir;
	}

```
If there are some extension points it would be possible to generate configuration files with custom content(application.properties with database settings, frequently configured properties etc) or new config files (Dockerfile etc).

**Comment by snicoll** [comment] 2019-02-01 09:11
@sivaprasadreddy thanks for the suggestion. We are currently working on a new infrastructure that would make this possible so I am going to close this as a duplicate of #340. Once that's available you can give that a try and open a more narrowed issue if you're experiencing a problem with the new API.

**Closed by snicoll** 2019-02-01 09:11 UTC
