### ISSUE TITLE
Has something changed in the API regarding the spring boot version?

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-io/initializr#1445] opened 2023-07-19 18:53 UTC
I am the author of `ttcli`, a command line tool that integrates with the Spring Initializer API to generate a Spring Boot project with some customizations on top to create a Thymeleaf project.

My tool has always worked fine, but recently I noticed that suddenly the generated `pom.xml` file now has `3.1.1.RELEASE` as version number instead of the `3.1.1` as it was before.
I read out the metadata from https://start.spring.io/metadata/client and allow the user to select the Spring Boot version. I then pass  the `id` of the version to the `/starter.zip` endpoint with the `bootVersion` request parameter set to the id of the version. This has always worked fine in the past, so I wonder what might have changed.

**Comment by wilkinsona** [comment] 2023-07-19 19:17
This is a duplicate of https://github.com/spring-io/initializr/issues/1373. You need to indicate, through the `Accept` header (`Accept: application/vnd.initializr.v2.2+json`), that your client accepts v2.2 of the metadata.

**Closed by wilkinsona** 2023-07-19 19:17 UTC
Labels: status: waiting-for-triage
