### ISSUE TITLE
No default constructor for entity

### ISSUE THREAD

**Issue by yooouuri** [spring-io/initializr#671] opened 2018-05-24 08:18 UTC
I'm getting the error `No default constructor for entity` when using kotlin.

After adding the `kotlin-jpa` plugin, the error is gone. That makes sense.

Without the plugin there will be no empty constructors in your models.

So when you choose JPA and Kotlin as language maybe add the plugin to the build.gradle?

**Comment by snicoll** [comment] 2018-05-24 08:29
Duplicate of #537

**Closed by snicoll** 2018-05-24 08:29 UTC
