### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by mdziczkowski** [spring-io/initializr#1579] opened 2024-11-03 22:39 UTC
Please update the generator and all dependencies to their newest versions.

Currently they require versions wth are outdated, no longer supported and because of that mostly unavaliable.

Additionally, it genrates a gradle file that may cause issues while running

**Comment by mhalbritter** [comment] 2024-11-04 07:27
Hello,

with which dependencies did you run into trouble?

**Comment by mhalbritter** [comment] 2024-11-04 12:57
I don't understand point 1 and 2. Could you please elaborate?

Point 3: We don't list every Java version. We provide an opinionated starting point for Spring Boot projects and those Java versions are the most widely used (17 is the minimum baseline, 21 is the next "LTS" after that, and 23 is the newest Java version).

Point 4: Do you mean the language or the build system? Of course there are other languages / build systems out there, but as said, we provide an opinionated starting point.

Point 5: Yes, and the reason for that is that those libraries in red doesn't support the selected Spring Boot version. There's nothing we can do about that.

If you find a dependency which is on start.spring.io, and we use an outdated version of it, please open an issue / PR and we get that fixed.

**Comment by mdziczkowski** [comment] 2024-11-04 14:29
**about point 1.**: I mentioned the page on with this issue has occured

**about point 2.**:

On the Spring.io website is listed a never version of Spring Boot then listed on the page in above point

**about point 3.**:

I had pointed it out because diferent Java have diferent version numering.

For example: Oracle Java: has version 24, while OpenJDK has 1.18

**about point 4.**: For example: Maven, etc.

**about point 5.**:

How about instead of seting a static version use "latest"?

**Comment by mhalbritter** [comment] 2024-11-04 15:54
> On the Spring.io website is listed a never version of Spring Boot then listed on the page in above point

start.spring.io:

![image](https://github.com/user-attachments/assets/b3910dc9-1d5f-44ff-93f8-c208ad3a7127)

https://spring.io/projects/spring-boot#learn

![image](https://github.com/user-attachments/assets/e554a0b1-6d70-44f9-853b-876682433c29)

All OSS supported Spring Boot versions (3.2.x and up) are on start.spring.io.

**Comment by mhalbritter** [comment] 2024-11-04 15:56
> For example: Oracle Java: has version 24, while OpenJDK has 1.18

There's no Java 24 released yet. It will be released on 2025-03-18, see https://openjdk.org/projects/jdk/24/.

Also there's no OpenJDK 1.18. There's OpenJDK 18 (https://openjdk.org/projects/jdk/18/), but we don't list every Java version between 17 and 23, just the "most important" ones.

**Comment by mhalbritter** [comment] 2024-11-04 15:57
> For example: Maven, etc.

There's support for Maven:

![Uploading image.png…]()

**Comment by mhalbritter** [comment] 2024-11-04 15:57
> How about instead of seting a static version use "latest"?

We won't do that as this leads to all sort of problems, and to builds which aren't reproducible.

**Closed** 2024-11-04 15:58 UTC
Labels: status: feedback-provided, status: waiting-for-triage

**Comment by mdziczkowski** [comment] 2024-11-18 11:13
> > For example: Oracle Java: has version 24, while OpenJDK has 1.18
> 
> There's no Java 24 released yet. It will be released on 2025-03-18, see https://openjdk.org/projects/jdk/24/.
> 
> Also there's no OpenJDK 1.18. There's OpenJDK 18 (https://openjdk.org/projects/jdk/18/), but we don't list every Java version between 17 and 23, just the "most important" ones.

I gave the version numbers as example reference.

On linux is such problem that in most cases the version number in the package manager is also displayed differently then when using (depending from java) `-v` or `--version` parameter
