### ISSUE TITLE
Display user selections as Spring CLI init parameters - for easy copy&paste.

### ISSUE THREAD

**Issue by aadrian** [spring-io/initializr#710] opened 2018-07-14 11:38 UTC
Hi,

When the user selects various options for the **Generate Project** button, please:
 1. display these selected options as Spring CLI init parameters
 2. maybe inside a `pre` tag *(under the **Generate Project** button)*
 3. so that the user can easily just copy and paste that CLI string into the terminal
 4. obtaining the same result as clicking the generate button and unzipping the generated zip.

This would:
 - greatly enhance the usability of this project 
 - help with testing, bug-fixing and reproducing bugs (or package/options problems), since that CLI String could be always attached to tickets for reproducibility.

Thanks in advance.

**Comment by wilkinsona** [comment] 2018-07-14 12:37
This is, largely, a duplicate of #66 but with a focus on `spring init` rather than `curl`.

**Comment by snicoll** [comment] 2018-07-16 07:51
Indeed. It should be noted that we don't want to provide explicit support for creating projects with a set of [dependencies and/or a specific Spring Boot version](https://github.com/spring-io/initializr#customize-form-inputs). The purpose of the service is to "start" (move forward) not reproduce things from the past. 

Dependencies come and go (and so are the available Spring Boot versions). Of course, we can support such link for quite some time but this is limited  (for instance, pre-1.2 code is gone already and we're going to clean 1.3 or 1.4 specific code at some point). 

Thanks for sharing the idea but adding such option in the UI is not consistent with this goal.

**Closed by snicoll** 2018-07-16 07:51 UTC

**Comment by odrotbohm** [comment] 2019-07-09 14:58
I don't see how your goal is subverted by the ability to link to a specific configuration of Initializr. [This Twitter conversation](https://twitter.com/rotnroll666/status/1148588327668523009) brings up the topic of being able to bookmark a preconfigured set of options again and I think it's a valid use case. Starting doesn't mean starting from scratch. I think it's reasonable to share a pointer to a set of predefined dependencies for user to add on the ones they need additionally.

This would also be incredible helpful for our very own reference documentation, helpful in guiding users how to create a minimal working example for particular projects or project combinations.

Not sure if there's a misunderstanding, but AFAIU the goal is not to provide a link to an immediate download (IIRC you could already do that via a curl request to an expanded URI template provided by the API), but merely a way to get to start.spring.io with some options preselected.

Also, isn't the link you provided indicating, that the customized start already *is* available for some of the settings?

**Comment by wilkinsona** [comment] 2019-07-09 15:07
I think we could do with a new issue for this as there are a few subtly different things that have been requested:

1. Display a `spring init` command in the Web UI based on the selections that have been made (this issue).
2. Display a `curl` command in the Web UI based on the selections that have been made (#66).
3. Provide support for linking to https://start.spring.io with preselected dependencies, Boot version, etc.

FWIW, I am currently in favor of 3 but I'm only one member of the team.

**Comment by odrotbohm** [comment] 2019-07-09 15:27
Good idea, I've created #944 for a more focussed discussion.
