### ISSUE TITLE
Support configuring Mockito java agent in java 21+ 

### ISSUE THREAD

**Issue by joshlong** [spring-io/initializr#1590] opened 2024-11-25 00:11 UTC
in Spring Boot 3.4 i'm getting 

```
Mockito is currently self-attaching to enable the inline-mock-maker. This will no longer work in future releases of the JDK. Please add Mockito as an agent to your build what is described in Mockito's documentation: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#0.3
WARNING: A Java agent has been loaded dynamically (/Users/jlong/.m2/repository/net/bytebuddy/byte-buddy-agent/1.15.10/byte-buddy-agent-1.15.10.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
``` 

basically, lots of scary logging indicating that agents won't work as they do now in the near-ish future. could we do something about it so users get the right experience OOTB? maybe on the Spring Initializr or in Spring Framework or Spring Boot itself? 

see also https://github.com/mockito/mockito/issues/3037

**Comment by wilkinsona** [comment] 2024-11-25 07:47
I think it has to be fixed with some build configuration. For Maven:

```xml
 <plugin>
     <groupId>org.apache.maven.plugins</groupId>
     <artifactId>maven-dependency-plugin</artifactId>
     <executions>
         <execution>
             <goals>
                 <goal>properties</goal>
             </goals>
         </execution>
     </executions>
 </plugin>
 <plugin>
     <groupId>org.apache.maven.plugins</groupId>
     <artifactId>maven-surefire-plugin</artifactId>
     <configuration>
         <argLine>@{argLine} -javaagent:${org.mockito:mockito-core:jar}</argLine>
     </configuration>
 </plugin>
```

For Gradle:

```groovy
 def mockitoAgent = configurations.create('mockitoAgent')

 dependencies {
     mockitoAgent('org.mockito:mockito-core') { isTransitive = false }
 }

 tasks {
     test {
         jvmArgs("-javaagent:${mockitoAgent.asPath}")
     }
 }
```

The difficulty here is that we have no signal that the user will actually use Mockito. It's part of `spring-boot-starter-test` but we have no way of knowing that it's actually going to be used. If it isn't, I'm not sure that we should be configuring it as an agent. There's also the problem of test execution in a user's IDE. If they're not delegating that execution to the build system, whatever we did there isn't going to help them.

**Comment by joshlong** [comment] 2024-11-25 22:42
with gradle, we could hide this from the user in our own plugin, right? so the only ugliness would be imposed on maven users

**Comment by wilkinsona** [comment] 2024-11-26 10:43
> could we have a checkbox on the Initializr that results in this plugin manipulation? sort of like we do with graalvm, which doesn't contribute a starter but a plugin? 

That's certainly technically possible.

> so the user could add Mockito and we'd help them out with this?

I wonder how confusing it would be to have a Mockito dependency and, even when you don't select it, you still end up with Mockito anyway through `spring-boot-starter-test`.

> with gradle, we could hide this from the user in our own plugin, right? so the only ugliness would be imposed on maven users

Yes, I think that's possible. It may even be possible to detect Mockito on a test task's classpath and only then set up the agent. A benefit of this approach is that it helps everyone using Gradle, not just those creating a project using start.spring.io. A downside of this approach is that it hides from the user what needs to be done to get Mockito working, leaving them wondering why it's fine on the command line yet broken in their IDE (assuming they're not delegating test execution to Gradle).

Given how widely Mockito's used across the Java ecosystem, it would be really nice to make this easier. I'm just not sure that start.spring.io or Spring Boot is the right place to do so. Reading through https://github.com/mockito/mockito/issues/3037, there appears to be some appetite for making this easier in build tools and, perhaps, in IDEs too so this becomes a question of what to do in the meantime and I'm not yet sure what, in anything, that should be.

**Comment by mhalbritter** [comment] 2024-11-29 12:16
> I'm just not sure that start.spring.io or Spring Boot is the right place to do so.

I agree. However, https://github.com/mockito/mockito/issues/3037#issuecomment-1588758555 reads like there won't be an easy solution to this in Maven. But this response is quite dated.

I found https://issues.apache.org/jira/browse/SUREFIRE-2287, which, if implemented, would ease the agent declaration in the POM.

> If it isn't, I'm not sure that we should be configuring it as an agent.

What would be the downside of always declaring the agent? `spring-boot-starter-test` always depends on it, and I guess the agent doesn't do anything if Mockito isn't used.

**Comment by mhalbritter** [comment] 2024-12-03 13:07
After some discussion and a lot of reading my opinion is that we shouldn't do something in the Spring Boot Gradle plugin and for the time being not do anything on the initializr.

If there's no other way to implement the Mockito functionality but to rely on an agent, I think the build tools and IDE vendors need to adapt and they need to start the JVM with the mockito agent attached.

If you want to get rid of the warning, [Andy has posted the workaround](https://github.com/spring-io/initializr/issues/1590#issuecomment-2497126455).

**Closed** 2024-12-03 13:08 UTC
Labels: status: declined

**Comment by cachescrubber** [comment] 2024-12-06 15:25
> After some discussion and a lot of reading my opinion is that we shouldn't do something in the Spring Boot Gradle plugin and for the time being not do anything on the initializr.

> If there's no other way to implement the Mockito functionality but to rely on an agent, I think the build tools and IDE vendors need to adapt and they need to start the JVM with the mockito agent attached.
> 
> If you want to get rid of the warning, [Andy has posted the workaround](https://github.com/spring-io/initializr/issues/1590#issuecomment-2497126455).



I would not call it a workaround.  It is the [official, documented solution the Mockito project is giving their users](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#mockito-instrumentation) to configure  their builds for inline-mock-maker instrumentation properly. After almost a year of discussion and consideration in https://github.com/mockito/mockito/issues/3037, this seems to be the way to go forward. 

`mockito-core` is a managed dependency of `spring-boot-starter-test`. In my opinion start.spring.io/spring-boot is responsible to configure the agent properly.
 
Since JDK 21 has been supported in spring-boot 3.2, even the most simple project generated on start.sproing.io ist causing this warning. This should be fixed.

**Comment by mhalbritter** [comment] 2024-12-09 08:08
I agree that this should be fixed, but I don't agree that this should be done on start.spring.io.

My opinion is that Surefire / Gradle should fix that - they can detect that `mockito-core` is on the classpath, and set the javaagent commandline flag accordingly. I haven't heard if they are willing to do that (I'll start a thread on the Maven dev mailing list). If they are absolutely against that, we can think about revising our decision.

**Comment by cachescrubber** [comment] 2024-12-09 09:42
Thank you @mhalbritter. Good to know the Spring Boot team is still looking for a solution. I usually do not reply to closed issued, but Friday I was finally preparing an issue regarding this topic. I found this closed issue last minute before posting a duplicate. I already prepared a [demo project](https://github.com/cachescrubber/demo-maven-mockito/pull/1) with the changes necessary to configure the java agent as a PR. Maybee it is still helpfull.

And, finally, in case the Spring Boot team has some connections to Jetbrains Spring Team -  [here is the Jetbrains Idea Backlog issue](https://youtrack.jetbrains.com/issue/IJPL-1181/JBR21-byteBuddyAgent-Dynamic-loading-of-agents-will-be-disallowed-XXEnableDynamicAgentLoading-required). Nothing happened on their side since a year AFAIK. So with JDK 21 and onwards every test execution in a spring boot project using the IDE's _run as_ dialog is producing this error. Like @wilkinsona  said, regardless of the maven or gradle configuration.

**Comment by michaldo** [comment] 2024-12-31 11:21
@mhalbritter could you paste link to "thread on the Maven dev mailing list"? I can't find it myself

**Comment by mhalbritter** [comment] 2025-01-07 08:17
I haven't started a thread yet - it's on my todo list.

**Comment by mhalbritter** [comment] 2025-02-06 08:44
@michaldo Here's the thread: https://lists.apache.org/thread/gp0hz9n08whcq430m5hhtl5kp41h0gfg

**Comment by nmck257** [comment] 2025-08-15 20:05
FWIW, looking at this topic today:
- IntelliJ IDEA has added support in 2025.2 to lift the relevant `argLine` config from Maven's surefire plugin and apply when running tests via IDE: https://youtrack.jetbrains.com/issue/IDEA-365387
- A default (Maven) project from `start.spring.io` will receive this warning when running tests (despite the tests not explicitly referencing Mockito)
- Tracing the Apache mailing list thread, I don't see movement on this topic since February

I haven't checked latest JDK/JEPs, but I'm wondering if there's a likelihood that the JDK will tighten this restriction before build tools have released nicer patterns. And if so, maybe this issue is worth reconsidering?

**Comment by rkrisztian** [comment] 2026-05-01 13:37
> My opinion is that Surefire / Gradle should fix that - they can detect that `mockito-core` is on the classpath, and set the javaagent commandline flag accordingly.

I suppose that will not scale well for the so many libraries that may need to do the same, therefore Gradle should focus on features that are agnostic to libraries. However, we can't keep pointing fingers either, someone should do something. Given that it's Spring Boot that depends on Mockito, Spring Boot users should either be aware of this through reference to the Mockito documentation, or through some setup that the Spring Boot plugin applies (e.g., by the project generator tool), but perhaps not directly: since the problem is coming from Mockito, they might create a Gradle plugin to ease the setup complexity, which then the Spring Boot plugin should apply.

**Comment by rkrisztian** [comment] 2026-05-01 13:42
By the way, here I would point out, too, that we should prefer the task configuration avoidance API in Gradle, see details in https://github.com/mockito/mockito/issues/3584#issuecomment-4359404735.
