### ISSUE TITLE
Fix Kotlin JPA compiler plugin configuration when using Maven

### ISSUE THREAD

**Issue by sdeleuze** [spring-io/initializr#863] opened 2019-03-13 10:18 UTC
As a follow-up of #537, when using Kotlin and JPA, the generated plugin configuration is:

```
<plugins>
	<plugin>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-maven-plugin</artifactId>
	</plugin>
	<plugin>
		<groupId>org.jetbrains.kotlin</groupId>
		<artifactId>kotlin-maven-noarg</artifactId>
		<version>${kotlin.version}</version>
		<configuration>
			<compilerPlugins>
				<plugin>jpa</plugin>
			</compilerPlugins>
		</configuration>
	</plugin>
	<plugin>
		<groupId>org.jetbrains.kotlin</groupId>
		<artifactId>kotlin-maven-plugin</artifactId>
		<configuration>
			<args>
				<arg>-Xjsr305=strict</arg>
			</args>
			<compilerPlugins>
				<plugin>spring</plugin>
			</compilerPlugins>
		</configuration>
		<dependencies>
			<dependency>
				<groupId>org.jetbrains.kotlin</groupId>
				<artifactId>kotlin-maven-allopen</artifactId>
				<version>${kotlin.version}</version>
			</dependency>
		</dependencies>
	</plugin>
</plugins>
```

Based on the documentation (and as validated in the [Kotlin tuto sources](https://github.com/spring-guides/tut-spring-boot-kotlin/blob/master/pom.xml)), I think the configuration should be:

```
<plugins>
	<plugin>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-maven-plugin</artifactId>
	</plugin>
	<plugin>
		<artifactId>kotlin-maven-plugin</artifactId>
		<groupId>org.jetbrains.kotlin</groupId>
		<configuration>
			<args>
				<arg>-Xjsr305=strict</arg>
			</args>
			<compilerPlugins>
				<plugin>spring</plugin>
				<plugin>jpa</plugin>
			</compilerPlugins>
		</configuration>
		<dependencies>
			<dependency>
				<groupId>org.jetbrains.kotlin</groupId>
				<artifactId>kotlin-maven-allopen</artifactId>
				<version>${kotlin.version}</version>
			</dependency>
			<dependency>
				<groupId>org.jetbrains.kotlin</groupId>
				<artifactId>kotlin-maven-noarg</artifactId>
				<version>${kotlin.version}</version>
			</dependency>
		</dependencies>
	</plugin>
</plugins>
```

This was raised via [this issue](https://github.com/spring-guides/tut-spring-boot-kotlin/issues/24) in the tuto.

**Comment by sdeleuze** [comment] 2019-03-13 10:43
If you agree with that change I can provide a PR.

**Comment by snicoll** [comment] 2019-03-13 11:04
@sdeleuze thanks for reporting the issue and offering a PR. It looks like you've confirmed the issue via the related issue so please go ahead. I don't know if the current setup used to be right and something changed in a recent kotlin version though. Keep in mind the site has to support several Kotlin generations.

**Comment by sdeleuze** [comment] 2019-03-13 14:28
Not sure if current setup has ever worked with Maven. If I use it on the Kotlin tuto, my tests are red.
The new setup seems to work on both Kotlin 1.2 and 1.3 so I will submit a PR with it.

**Comment by snicoll** [comment] 2019-03-14 19:41
Closing in favour of PR #868

**Closed by snicoll** 2019-03-14 19:41 UTC
Labels: type: bug
