### ISSUE TITLE
Error during installation on Windows 10

### ISSUE THREAD

**Issue by pbvelikov** [spring-io/initializr#1410] opened 2023-05-04 16:39 UTC
Hi Team,

When executing this command (on my Windows 10 laptop):

`mvnw clean install`

I get this error:

```
[ERROR] Failures:
[ERROR]   GroovyDslGradleBuildAssertTests.containsOnlyExtProperties:85
Expecting actual:
  "plugins {
        id 'com.example' version '1.0.0.RELEASE'
        id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
        mavenCentral()
}

ext {
        set('acmeVersion', "Brussels.SR2")
}

dependencies {
        implementation 'com.example.acme:library'
        testImplementation 'com.example.acme:library-test'
}

dependencyManagement {
        imports {
                mavenBom "com.example.acme:library-bom:${acmeVersion}"
        }
}

"
to contain:
  "ext {
        set('acmeVersion', "Brussels.SR2")
}"
[INFO]
[ERROR] Tests run: 124, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Spring Initializr :: Generator (Test Infrastructure) 0.20.0-SNAPSHOT:
[INFO]
[INFO] Spring Initializr :: Generator (Test Infrastructure) FAILURE [  9.133 s]
[INFO] Spring Initializr :: Generator (Spring projects) ... SKIPPED
[INFO] Spring Initializr :: Web ........................... SKIPPED
[INFO] Spring Initializr :: Actuator ...................... SKIPPED
[INFO] Spring Initializr :: Docs .......................... SKIPPED
[INFO] Spring Initializr :: Service (Sample) .............. SKIPPED
[INFO] Spring Initializr :: Version Resolver .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.420 s
[INFO] Finished at: 2023-05-04T16:06:20+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0:test (default-test) on project initializr-generator-test: There are test failures.
[ERROR]
[ERROR] Please refer to D:\PelcoDOCs\Development\BOJKO\Initializr\initializr-main\initializr-generator-test\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
Please advise what the problem is and how to fix it?
The installation stops and I cannot continue further.

Looking forward to your support!

**Comment by wilkinsona** [comment] 2023-05-04 17:04
Assuming that you used `git clone` to get the source onto your laptop, I would guess that the handling of line endings isn't configured as required. See https://github.com/spring-io/initializr/issues/1150#issuecomment-1527837891.

**Comment by pbvelikov** [comment] 2023-05-04 17:08
Hi @wilkinsona ,

I didn't use git clone. I downloaded the code using the Download ZIP link.
Is the problem the same in this case?

**Comment by wilkinsona** [comment] 2023-05-04 17:10
Yes. This is a duplicate of #1150.

**Closed by wilkinsona** 2023-05-04 17:10 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage

**Comment by pbvelikov** [comment] 2023-05-04 17:18
OK, Thank you!
I will git clone it using the right git client end line handling and will let you know the result.

**Comment by pbvelikov** [comment] 2023-05-04 17:24
I git-cloned it properly and all problems were solved. Success after compilation:

![success](https://user-images.githubusercontent.com/33320876/236281300-084ade88-3bef-4bc5-ba44-47b2fea262a4.png)

Thank you!

**Comment by wilkinsona** [comment] 2023-05-04 17:29
Great! Thanks for letting us know.
