### ISSUE TITLE
Initializr offers Java 13, but the generated project is based on Java 11

### ISSUE THREAD

**Issue by Shpota** [spring-io/initializr#1036] opened 2019-11-08 09:52 UTC
It is possible to generate a Spring Boot project based on Java 13 and Gradle on [start.spring.io](https://start.spring.io/). However, the generated project is based on Java 11. 

I guess it is because the latest Gradle (v5.6.4 at the moment) doesn't support Java 13. At the same time, it is misleading and has to be fixed.

**Comment by snicoll** [comment] 2019-11-08 10:01
> At the same time, it is misleading and has to be fixed.

What has to be fixed exactly? Gradle doesn't support Java 13 so letting you going through will force you to use Java 13 and doing so will break for the reason you've exposed.

**Comment by Shpota** [comment] 2019-11-08 10:17
I generate a project specifying Java 13 as a target and the tool generates a Java 11 based project. Is it expected behavior? If the starter doesn't support Java 13 (due to the fact that Gradle doesn't support it) why misleading users by offering Java 13? 

I guess you can remove this option until Java 13 is supported by Gradle. Or alternatively, the project might be generated based on `gradle-6.0-rc-1` notifying users that they will get an RC based project.

**Comment by snicoll** [comment] 2019-11-08 10:23
Thanks for the feedback. We don't do such validation as the service is a multi-clients effort and you wouldn't get an option disappearing from the command line anyway. Spring Boot does not officially support Gradle 6 yet and won't in the `2.1.x` line so that would be incomplete as well anyway.

Duplicate of https://github.com/spring-io/start.spring.io/issues/250

**Closed by snicoll** 2019-11-08 10:23 UTC
Labels: status: waiting-for-feedback

**Comment by Shpota** [comment] 2019-11-08 10:32
Thank you for the information. Will 2.2.x support Gradle 6?

**Comment by snicoll** [comment] 2019-11-08 10:34
You can watch this issue: https://github.com/spring-projects/spring-boot/issues/18663
