### ISSUE TITLE
Allow users to display documentation/reference links

### ISSUE THREAD

**Issue by torstenwalter** [spring-io/initializr#695] opened 2018-06-29 06:14 UTC
Spring Initializr has a nice feature that allows to declare links to guides or reference documentation (https://docs.spring.io/initializr/docs/current/reference/htmlsingle/#create-instance-dependencies-link).
Unfortunately I they are not rendered on the homepage. Would be great if they could be shown or if the user has the ability to select if they want to see those links.

**Comment by wilkinsona** [comment] 2018-06-29 09:30
Thanks for the suggestion, but this is a duplicate of #607 that we declined. Our preferred approach is being tracked by #353.

**Closed by wilkinsona** 2018-06-29 09:30 UTC
