### ISSUE TITLE
Kotlin annotation processor best practice ?

### ISSUE THREAD

**Issue by LifeIsStrange** [spring-io/initializr#1169] opened 2021-01-13 21:19 UTC
For Kottlin, Spring Initializer set annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
The Kotlin doc sems to indicate that Kapt() should be preffered instead 
cf: "If you previously used the Android support for annotation processors, replace usages of the annotationProcessor configuration with kapt. If your project contains Java classes, kapt will also take care of them."

and also add the Kapt plugin.
https://kotlinlang.org/docs/reference/kapt.html#using-in-gradle

I have no Idea (and google is not helpful)  what are the real pros and cons of annotationProcessor vs Kapt but heuristically, Spring Initializer should switch to it or at least add the plugin ?

**Comment by snicoll** [comment] 2021-01-14 07:28
@LifeIsStrange thank you for the report, this is a duplicate of #438

**Closed by snicoll** 2021-01-14 07:28 UTC
Labels: status: waiting-for-triage
